version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network
  asynqmon:
    image: hibiken/asynqmon:latest
    container_name: asynqmon-server
    ports:
      - "8080:8080"
    networks:
      - redis-network
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
          - redis

volumes:
  redis-data:
    driver: local

networks:
  redis-network:
    driver: bridge
